FROM golang:alpine as builder

WORKDIR /app
COPY go.* ./
RUN go mod download
COPY . .
RUN apk update && apk add upx ca-certificates openssl && update-ca-certificates
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o /bin/app ./cmd/app/main.go
RUN upx -9 /bin/app

FROM gcr.io/distroless/static:nonroot
WORKDIR /app/
COPY --from=builder /bin/app /bin/app
COPY --from=builder --chown=nonroot /app/config /app/config
ENTRYPOINT ["/bin/app"]